/**
 * Hand-written types that match the initial schema migration.
 *
 * To regenerate from a running Supabase project, run:
 *   npm run db:types
 *
 * Do not edit this file manually once regenerated — your changes will be overwritten.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          full_name: string | null
          phone: string | null
          default_shipping_address: Json | null
          stripe_customer_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          full_name?: string | null
          phone?: string | null
          default_shipping_address?: Json | null
          stripe_customer_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          full_name?: string | null
          phone?: string | null
          default_shipping_address?: Json | null
          stripe_customer_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      children: {
        Row: {
          id: string
          parent_id: string
          name: string
          birth_date: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          parent_id: string
          name: string
          birth_date: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          parent_id?: string
          name?: string
          birth_date?: string
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'children_parent_id_fkey'
            columns: ['parent_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
        ]
      }
      boxes: {
        Row: {
          id: string
          slug: string
          name: string
          description: string | null
          age_min_months: number
          age_max_months: number
          monthly_price: number
          stripe_price_id: string | null
          cover_image_url: string | null
          sort_order: number
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          slug: string
          name: string
          description?: string | null
          age_min_months: number
          age_max_months: number
          monthly_price: number
          stripe_price_id?: string | null
          cover_image_url?: string | null
          sort_order?: number
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          slug?: string
          name?: string
          description?: string | null
          age_min_months?: number
          age_max_months?: number
          monthly_price?: number
          stripe_price_id?: string | null
          cover_image_url?: string | null
          sort_order?: number
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      subscriptions: {
        Row: {
          id: string
          profile_id: string
          child_id: string
          box_id: string
          stripe_subscription_id: string | null
          status: Database['public']['Enums']['subscription_status']
          current_period_start: string | null
          current_period_end: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          profile_id: string
          child_id: string
          box_id: string
          stripe_subscription_id?: string | null
          status?: Database['public']['Enums']['subscription_status']
          current_period_start?: string | null
          current_period_end?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          profile_id?: string
          child_id?: string
          box_id?: string
          stripe_subscription_id?: string | null
          status?: Database['public']['Enums']['subscription_status']
          current_period_start?: string | null
          current_period_end?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'subscriptions_profile_id_fkey'
            columns: ['profile_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'subscriptions_child_id_fkey'
            columns: ['child_id']
            isOneToOne: false
            referencedRelation: 'children'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'subscriptions_box_id_fkey'
            columns: ['box_id']
            isOneToOne: false
            referencedRelation: 'boxes'
            referencedColumns: ['id']
          },
        ]
      }
      orders: {
        Row: {
          id: string
          profile_id: string
          subscription_id: string | null
          stripe_payment_intent_id: string | null
          status: Database['public']['Enums']['order_status']
          total_amount: number
          shipping_address: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          profile_id: string
          subscription_id?: string | null
          stripe_payment_intent_id?: string | null
          status?: Database['public']['Enums']['order_status']
          total_amount: number
          shipping_address: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          profile_id?: string
          subscription_id?: string | null
          stripe_payment_intent_id?: string | null
          status?: Database['public']['Enums']['order_status']
          total_amount?: number
          shipping_address?: Json
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'orders_profile_id_fkey'
            columns: ['profile_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'orders_subscription_id_fkey'
            columns: ['subscription_id']
            isOneToOne: false
            referencedRelation: 'subscriptions'
            referencedColumns: ['id']
          },
        ]
      }
      order_items: {
        Row: {
          id: string
          order_id: string
          box_id: string
          quantity: number
          unit_price: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          order_id: string
          box_id: string
          quantity?: number
          unit_price: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          order_id?: string
          box_id?: string
          quantity?: number
          unit_price?: number
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'order_items_order_id_fkey'
            columns: ['order_id']
            isOneToOne: false
            referencedRelation: 'orders'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'order_items_box_id_fkey'
            columns: ['box_id']
            isOneToOne: false
            referencedRelation: 'boxes'
            referencedColumns: ['id']
          },
        ]
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: {
      subscription_status: 'trialing' | 'active' | 'paused' | 'past_due' | 'cancelled'
      order_status: 'pending' | 'paid' | 'shipped' | 'delivered' | 'cancelled'
    }
    CompositeTypes: Record<string, never>
  }
}

// Convenience helpers — use these instead of reaching into Database directly.
export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row']

export type Enums<T extends keyof Database['public']['Enums']> =
  Database['public']['Enums'][T]
